FROM alpine:3.19

RUN apk add --no-cache \
    kea \
    kea-dhcp4 \
    kea-dhcp6 \
    kea-ctrl-agent \
    busybox-extras

RUN mkdir -p /run/kea && \
    chown -R 100:100 /run/kea && \
    chmod 750 /run/kea

RUN mkdir -p /etc/kea
COPY kea-dhcp4.conf /etc/kea/kea-dhcp4.conf
COPY kea-dhcp6.conf /etc/kea/kea-dhcp6.conf
COPY kea-ctrl-agent.conf /etc/kea/kea-ctrl-agent.conf
