FROM alpine:3.19

RUN apk add --no-cache \
    kea \
    kea-dhcp4 \
    kea-dhcp6 \
    kea-ctrl-agent \
    gettext \
    busybox-extras

RUN mkdir -p /run/kea && \
    chown -R 100:100 /run/kea && \
    chmod 750 /run/kea

RUN mkdir -p /etc/kea /templates
COPY templates/* /templates/
